---
- name: upload package on cvmfs
  hosts: cvmfs
  become: true
  vars:
    package: '{{ image }}__{{ flavor }}_{{ version }}'
  tasks:

    - name: Create a virtualenv and install swift cli        
      pip:
        name: [ "setuptools_rust","python-openstackclient","python-swiftclient" ]
        virtualenv: /tmp/swift_venv
        virtualenv_command: python3 -m venv

    - name: Package to download
      debug:
        msg: '{{ package }}'

    - name: Download container in the cvmfs buffer
      shell: >
        /tmp/swift_venv/bin/swift download
        --os-auth-token '{{ os_token }}'
        --os-storage-url '{{ os_storage_url }}'
        galaxy_flavors
        '{{ package }}'
      args:
        executable: /bin/bash
        chdir: /buffer

    - name: Open cvmfs transaction
      shell: cvmfs_server transaction tools.elixir-italy-cvmfs
      args:
        executable: /bin/bash
        chdir: /buffer

    - name: Move package from cvmfs buffer to cvmfs
      shell: mv -f {{ package }} /cvmfs/tools.elixir-italy-cvmfs/dump/
      args:
        executable: /bin/bash
        chdir: /buffer
    
    - name: CVMFS publish
      shell: cvmfs_server publish tools.elixir-italy-cvmfs
      args:
        executable: /bin/bash
        chdir: /buffer
    
    #- name: Clean container 
    #  shell: >
    #    /tmp/swift_venv/bin/swift delete
    #    galaxy_flavors
    #    -p '{{ package  }}'
    #    --os-auth-token '{{ os_token }}'
    #    --os-storage-url '{{ os_storage_url }}'
    #  args:
    #    executable: /bin/bash
    #    chdir: /buffer
