---
- name: upload package on swift
  hosts: galaxyservers
  become: true
  tasks:
    - name: create dump dir
      file:
        path: /export/dump
        state: directory

    - name: create virtualenv and install swift cli
      pip:
        name: ["setuptools_rust", "python-openstackclient", "python-swiftclient"]
        virtualenv: /tmp/swift_venv
        virtualenv_command: python3 -m venv

    - name: upload package on the galaxy_flavors swift container
      shell: /tmp/swift_venv/bin/swift upload --os-auth-token '{{ os_token }}' --os-storage-url '{{ os_storage_url }}' -S 1073741824 --insecure galaxy_flavors galaxy-express*
      args:
        chdir: /export/dump
