---
- name: upload package on swift
  hosts: galaxyservers
  become: true
  tasks:
    - name: upload package on the galaxy_flavors swift container 
      shell: swift upload -S 1073741824  --insecure galaxy_flavors galaxy-express*
      args:
        chdir: /tmp/dump

    



          
            
